[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "minipy-tools"
version = "0.1.4"
description = "Minipy is a CLI tool that combines Python tools and games into one program. I created this program to become better in Python and to learn new things. I used some blogs and YouTube videos to make the base of some tools/games, then I customized them and experimented with them."
authors = [{name = "Noé Ballieu", email = "nonobal2812@gmail.com"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
keywords = ["cli", "tools", "games", "terminal", "useful", "utility", "python"]
dependencies = [
    "inquirer",
    "click",
    "python-dotenv",
    "requests",
    "pypdf",
    "Pillow",
    "qrcode",
    "yt-dlp[default,deno]",
    "pynput",
    "keyboard",
    "pyautogui",
    "spotdl",
    "playsound",
    "python-dateutil",
    "blessed",
    "english-words",
    "wordfreq"
]

[project.optional-dependencies]
audio = ["pyaudio"]

[project.scripts]
minipy = "minipy.main:main"

[tool.setuptools.packages.find]
include = ["minipy*"]

[tool.setuptools.package-data]
minipy = ["assets/*.mp3"]
