[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "minipykit"
version = "0.1.0"
description = ""
authors = [{name = "Noé Ballieu", email = "nonobal2812@gmail.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirer",
    "click",
    "python-dotenv",
    "requests"
]

[project.scripts]
minipy = "minipy.main:main"